<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.1">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
    	<Nullable>disable</Nullable>
    </PropertyGroup>

	<ItemGroup>
		<LaunchProfilePlugin Include="tomat.enablemod" />
		<LaunchProfilePlugin Include="lolxd87.splashskip" />
		<LaunchProfilePlugin Include="tomat.assethotreloading" />
	  <Reference Include="StructureHelper">
	    <HintPath>lib\StructureHelper.dll</HintPath>
	  </Reference>
	  <Reference Include="SubworldLibrary">
	    <HintPath>lib\SubworldLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>