using Terraria.Audio;

namespace NeoParacosm.Core.Systems.Assets;

/// <summary>
/// Generated by Claude
/// Provides readable aliases for Terraria SoundIDs with names reflecting their purpose or associated items.
/// Based on official wiki data: https://terraria.wiki.gg/wiki/Sound_IDs
/// </summary>
public static class SFX
{
    // ==================== CORE SOUNDS ====================

    /// <summary>Most blocks and walls when struck</summary>
    public static readonly SoundStyle Dig = SoundID.Dig;

    // ==================== ITEM SOUNDS ====================

    /// <summary>Most swung weapons, tools and consumables, hooks</summary>
    public static readonly SoundStyle Swing = SoundID.Item1;

    /// <summary>Most pet-summoning items, solid food items</summary>
    public static readonly SoundStyle PetSummon = SoundID.Item2;

    /// <summary>Potions, liquid food items</summary>
    public static readonly SoundStyle PotionDrink = SoundID.Item3;

    /// <summary>Bewitching Table, Crystal Ball, Demon Heart, Enchanted Sundial, Fallen Star, Life Crystal, Life Fruit, Torch God's Favor</summary>
    public static readonly SoundStyle CrystalBall = SoundID.Item4;

    /// <summary>Most bows and repeaters, Antlion attack</summary>
    public static readonly SoundStyle BowShot = SoundID.Item5;

    /// <summary>Magic Mirror, Ice Mirror, Cell Phone, Magic Conch, Demon Conch, Shellphone, Recall Potion, Teleportation Potion, Potion of Return, Gender Change Potion, Teleporter, Pylons</summary>
    public static readonly SoundStyle MagicMirror = SoundID.Item6;

    /// <summary>Most boomerangs, Paladin's Hammer, Leaf Blower</summary>
    public static readonly SoundStyle Boomerang = SoundID.Item7;

    /// <summary>Blood Squid summoned, Book of Skulls, Chaos Elemental teleport, Demon Scythe, Vilethorn, Wand of Sparking, and many magical items</summary>
    public static readonly SoundStyle MagicCast = SoundID.Item8;

    /// <summary>Crystal Storm, Magic Missile, Sky Fracture, Star Cannon</summary>
    public static readonly SoundStyle CrystalStorm = SoundID.Item9;

    /// <summary>Golem Fist, Harpoon, Piranha Gun, Prime Cannon bomb launched</summary>
    public static readonly SoundStyle Harpoon = SoundID.Item10;

    /// <summary>Most guns, magic guns and launchers</summary>
    public static readonly SoundStyle Gunshot = SoundID.Item11;

    /// <summary>Gastropod attack, Heat Ray, Laser Rifle, Nebula Floater attack, Probe attack, Zapinator</summary>
    public static readonly SoundStyle LaserRifle = SoundID.Item12;

    /// <summary>Aqua Scepter, Golden Shower, Last Prism, Rocket Boots hover</summary>
    public static readonly SoundStyle AquaScepter = SoundID.Item13;

    /// <summary>Beenade, Bomb, Dynamite, Grenade, Sticky Bomb, Prime Cannon, and other explosives</summary>
    public static readonly SoundStyle Explosion = SoundID.Item14;

    /// <summary>Phaseblades, Phasesabers, Last Prism, Medusa Head</summary>
    public static readonly SoundStyle PhaseBlade = SoundID.Item15;

    /// <summary>Whoopie Cushion, Companion Cube, Gas Trap, Fart double jump items</summary>
    public static readonly SoundStyle CompanionCube = SoundID.Item16;

    /// <summary>Black Recluse attack, Dart Trap activated, Hornet attack, Queen Bee attack, Spiked Slime attack</summary>
    public static readonly SoundStyle DartTrap = SoundID.Item17;

    /// <summary>Most swung weapons, tools and consumables, hooks</summary>
    public static readonly SoundStyle SwingAlt1 = SoundID.Item18;

    /// <summary>Most swung weapons, tools and consumables, hooks</summary>
    public static readonly SoundStyle SwingAlt2 = SoundID.Item19;

    /// <summary>Cursed Flames, Flamelash, Flower of Fire, Frost Staff, Magnet Sphere, Nebula Blaze</summary>
    public static readonly SoundStyle CursedFlames = SoundID.Item20;

    /// <summary>Water Bolt</summary>
    public static readonly SoundStyle WaterBolt = SoundID.Item21;

    /// <summary>Most drills and chainsaws</summary>
    public static readonly SoundStyle Drill = SoundID.Item22;

    /// <summary>Most drills and chainsaws, Lawn Mower</summary>
    public static readonly SoundStyle Chainsaw = SoundID.Item23;

    /// <summary>Hovering with Celestial Starboard, Fairy Boots, Frostspark Boots, Lightning Boots, Spectre Boots or Terraspark Boots</summary>
    public static readonly SoundStyle BootsHover = SoundID.Item24;

    /// <summary>Most mount-summoning items, Fairy Bell, Superheated Blood</summary>
    public static readonly SoundStyle MountSummon = SoundID.Item25;

    /// <summary>Harp, Magical Harp</summary>
    public static readonly SoundStyle Harp = SoundID.Item26;

    /// <summary>Player takes damage with full Frost armor set equipped, Frost Daggerfish impact, Magical Ice Block struck</summary>
    public static readonly SoundStyle FrostArmor = SoundID.Item27;

    /// <summary>Ice Elemental, Ice Rod, Rainbow Rod, Rune Wizard</summary>
    public static readonly SoundStyle IceRod = SoundID.Item28;

    /// <summary>Mana Crystal</summary>
    public static readonly SoundStyle ManaCrystal = SoundID.Item29;

    /// <summary>Magical Ice Block placed</summary>
    public static readonly SoundStyle IceBlockPlace = SoundID.Item30;

    /// <summary>Clockwork Assault Rifle</summary>
    public static readonly SoundStyle ClockworkRifle = SoundID.Item31;

    /// <summary>Most wings, Bat Scepter</summary>
    public static readonly SoundStyle Wings = SoundID.Item32;

    /// <summary>Destroyer Death Laser attack, Golem Head Eye Beam attack, Prime Laser attack, Retinazer Eye Laser attack</summary>
    public static readonly SoundStyle DeathLaser = SoundID.Item33;

    /// <summary>Clentaminator, Elf Melter, Flamethrower</summary>
    public static readonly SoundStyle Flamethrower = SoundID.Item34;

    /// <summary>Bell</summary>
    public static readonly SoundStyle Bell = SoundID.Item35;

    /// <summary>Boomstick, Onyx Blaster, Quad-Barrel Shotgun, Shotgun</summary>
    public static readonly SoundStyle Shotgun = SoundID.Item36;

    /// <summary>Reforging an item, Sharpening Station</summary>
    public static readonly SoundStyle Reforge = SoundID.Item37;

    /// <summary>Tactical Shotgun</summary>
    public static readonly SoundStyle TacticalShotgun = SoundID.Item38;

    /// <summary>Razorpine, Scourge of the Corruptor, Vampire Knives</summary>
    public static readonly SoundStyle Razorpine = SoundID.Item39;

    /// <summary>S.D.M.G., Sniper Rifle</summary>
    public static readonly SoundStyle SniperRifle = SoundID.Item40;

    /// <summary>Chain Gun, Gatligator, Handgun, Phoenix Blaster, Revolver, Venus Magnum</summary>
    public static readonly SoundStyle ChainGun = SoundID.Item41;

    /// <summary>Flaming Wood fired, Missile fired</summary>
    public static readonly SoundStyle MissileLaunch = SoundID.Item42;

    /// <summary>Amber Staff, Amethyst Staff, Diamond Staff, Emerald Staff, Ruby Staff, Sapphire Staff, Topaz Staff, and other gem staffs</summary>
    public static readonly SoundStyle GemStaff = SoundID.Item43;

    /// <summary>Pirate Staff, Pygmy Staff, Raven Staff, Slime Staff, Stardust Dragon Staff, Tempest Staff, Vampire Frog Staff, Xeno Staff</summary>
    public static readonly SoundStyle SummonStaff = SoundID.Item44;

    /// <summary>Houndius Shootius Fireball Impact</summary>
    public static readonly SoundStyle HoundiusShootius = SoundID.Item45;

    /// <summary>Queen Spider Staff, Staff of the Frost Hydra</summary>
    public static readonly SoundStyle QueenSpiderStaff = SoundID.Item46;

    /// <summary>The Axe</summary>
    public static readonly SoundStyle TheAxe = SoundID.Item47;

    /// <summary>Snow Block and Slush Block struck</summary>
    public static readonly SoundStyle SnowBlockStrike1 = SoundID.Item48;

    /// <summary>Snow Block and Slush Block struck</summary>
    public static readonly SoundStyle SnowBlockStrike2 = SoundID.Item49;

    /// <summary>Ice Block struck</summary>
    public static readonly SoundStyle IceBlockStrike = SoundID.Item50;

    /// <summary>Snowball impact</summary>
    public static readonly SoundStyle Snowball = SoundID.Item51;

    /// <summary>Minecart Track struck</summary>
    public static readonly SoundStyle MinecartTrack = SoundID.Item52;

    /// <summary>Minecart hits track</summary>
    public static readonly SoundStyle MinecartHit = SoundID.Item53;

    /// <summary>Bubble pop, Toxic Bubble pop</summary>
    public static readonly SoundStyle BubblePop = SoundID.Item54;

    /// <summary>Minecart slows down</summary>
    public static readonly SoundStyle MinecartSlow = SoundID.Item55;

    /// <summary>Minecart bounces</summary>
    public static readonly SoundStyle MinecartBounce = SoundID.Item56;

    /// <summary>Meowmere projectile impact, star minigame while generating a Zenith world</summary>
    public static readonly SoundStyle Meowmere = SoundID.Item57;

    /// <summary>Meowmere projectile impact, star minigame while generating a Zenith world</summary>
    public static readonly SoundStyle MeowmereAlt = SoundID.Item58;

    /// <summary>Money Trough</summary>
    public static readonly SoundStyle MoneyTrough = SoundID.Item59;

    /// <summary>Terra Blade, Sand Elemental Ancient Storm attack, Blood Thorn, Houndius Shootius Fireball</summary>
    public static readonly SoundStyle TerraBlade = SoundID.Item60;

    /// <summary>Grenade Launcher, Pew-matic Horn</summary>
    public static readonly SoundStyle GrenadeLauncher = SoundID.Item61;

    /// <summary>Grenade explosion</summary>
    public static readonly SoundStyle GrenadeExplosion = SoundID.Item62;

    /// <summary>Blowpipe</summary>
    public static readonly SoundStyle Blowpipe = SoundID.Item63;

    /// <summary>Blowgun, The Grand Design</summary>
    public static readonly SoundStyle Blowgun = SoundID.Item64;

    /// <summary>Item65 - unused</summary>
    public static readonly SoundStyle Unused65 = SoundID.Item65;

    /// <summary>Nimbus Rod</summary>
    public static readonly SoundStyle NimbusRod = SoundID.Item66;

    /// <summary>Rainbow Gun</summary>
    public static readonly SoundStyle RainbowGun = SoundID.Item67;

    /// <summary>Item68 - unused</summary>
    public static readonly SoundStyle Unused68 = SoundID.Item68;

    /// <summary>Staff of Earth</summary>
    public static readonly SoundStyle StaffOfEarth = SoundID.Item69;

    /// <summary>Boulder impact</summary>
    public static readonly SoundStyle BoulderImpact = SoundID.Item70;

    /// <summary>Death Sickle</summary>
    public static readonly SoundStyle DeathSickle = SoundID.Item71;

    /// <summary>Shadowbeam Staff</summary>
    public static readonly SoundStyle ShadowbeamStaff = SoundID.Item72;

    /// <summary>Inferno Fork</summary>
    public static readonly SoundStyle InfernoFork = SoundID.Item73;

    /// <summary>Inferno Bolt impact</summary>
    public static readonly SoundStyle InfernoBolt = SoundID.Item74;

    /// <summary>Pulse Bow, Charged Blaster Cannon</summary>
    public static readonly SoundStyle PulseBow = SoundID.Item75;

    /// <summary>Hornet Staff</summary>
    public static readonly SoundStyle HornetStaff = SoundID.Item76;

    /// <summary>Imp Staff</summary>
    public static readonly SoundStyle ImpStaff = SoundID.Item77;

    /// <summary>Queen Spider Staff, Lunar Portal Staff, Rainbow Crystal Staff</summary>
    public static readonly SoundStyle QueenSpider = SoundID.Item78;

    /// <summary>Fuzzy Carrot</summary>
    public static readonly SoundStyle FuzzyCarrot = SoundID.Item79;

    /// <summary>Scaly Truffle</summary>
    public static readonly SoundStyle ScalyTruffle = SoundID.Item80;

    /// <summary>Slimy Saddle</summary>
    public static readonly SoundStyle SlimySaddle = SoundID.Item81;

    /// <summary>Optic Staff, Nightglow, Terraprisma</summary>
    public static readonly SoundStyle OpticStaff = SoundID.Item82;

    /// <summary>Spider Staff</summary>
    public static readonly SoundStyle SpiderStaff = SoundID.Item83;

    /// <summary>Razorblade Typhoon</summary>
    public static readonly SoundStyle RazorbladeTyphoon = SoundID.Item84;

    /// <summary>Bubble Gun</summary>
    public static readonly SoundStyle BubbleGun = SoundID.Item85;

    /// <summary>Item86 - unused</summary>
    public static readonly SoundStyle Unused86 = SoundID.Item86;

    /// <summary>Item87 - unused</summary>
    public static readonly SoundStyle Unused87 = SoundID.Item87;

    /// <summary>Meteor Staff, Lunar Flare</summary>
    public static readonly SoundStyle MeteorStaff = SoundID.Item88;

    /// <summary>Meteor impact</summary>
    public static readonly SoundStyle MeteorImpact = SoundID.Item89;

    /// <summary>Brain Scrambler</summary>
    public static readonly SoundStyle BrainScrambler = SoundID.Item90;

    /// <summary>Laser Machinegun</summary>
    public static readonly SoundStyle LaserMachinegun = SoundID.Item91;

    /// <summary>Electrosphere Launcher, Advanced Combat Techniques, Cat License, Dog License, Bunny License, Shimmer consumable items</summary>
    public static readonly SoundStyle ElectrosphereLauncher = SoundID.Item92;

    /// <summary>Item93 - unused</summary>
    public static readonly SoundStyle Unused93 = SoundID.Item93;

    /// <summary>Electrosphere Missile impact</summary>
    public static readonly SoundStyle ElectrosphereMissile = SoundID.Item94;

    /// <summary>Xenopopper</summary>
    public static readonly SoundStyle Xenopopper = SoundID.Item95;

    /// <summary>Xenopopper projectile</summary>
    public static readonly SoundStyle XenopopperProjectile = SoundID.Item96;

    /// <summary>The Bee's Knees</summary>
    public static readonly SoundStyle BeesKnees = SoundID.Item97;

    /// <summary>Dart Pistol</summary>
    public static readonly SoundStyle DartPistol = SoundID.Item98;

    /// <summary>Dart Rifle</summary>
    public static readonly SoundStyle DartRifle = SoundID.Item99;

    /// <summary>Clinger Staff</summary>
    public static readonly SoundStyle ClingerStaff = SoundID.Item100;

    /// <summary>Crystal Vile Shard</summary>
    public static readonly SoundStyle CrystalVileShard = SoundID.Item101;

    /// <summary>Shadowflame Bow, Aerial Bane</summary>
    public static readonly SoundStyle ShadowflameBow = SoundID.Item102;

    /// <summary>Shadowflame Hex Doll</summary>
    public static readonly SoundStyle ShadowflameHexDoll = SoundID.Item103;

    /// <summary>Item104 - unused</summary>
    public static readonly SoundStyle Unused104 = SoundID.Item104;

    /// <summary>Star Wrath</summary>
    public static readonly SoundStyle StarWrath = SoundID.Item105;

    /// <summary>Toxic Flask, Tree Globe, World Globe</summary>
    public static readonly SoundStyle ToxicFlask = SoundID.Item106;

    /// <summary>Toxic Flask impact, Tree Globe impact, World Globe impact</summary>
    public static readonly SoundStyle ToxicFlaskImpact = SoundID.Item107;

    /// <summary>Nail Gun</summary>
    public static readonly SoundStyle NailGun = SoundID.Item108;

    /// <summary>Crystal Serpent</summary>
    public static readonly SoundStyle CrystalSerpent = SoundID.Item109;

    /// <summary>Crystal Charge impact</summary>
    public static readonly SoundStyle CrystalCharge = SoundID.Item110;

    /// <summary>Toxikarp</summary>
    public static readonly SoundStyle Toxikarp = SoundID.Item111;

    /// <summary>Item112 - unused</summary>
    public static readonly SoundStyle Unused112 = SoundID.Item112;

    /// <summary>Deadly Sphere Staff</summary>
    public static readonly SoundStyle DeadlySphereStaff = SoundID.Item113;

    /// <summary>Portal Gun</summary>
    public static readonly SoundStyle PortalGun = SoundID.Item114;

    /// <summary>Portal Gun</summary>
    public static readonly SoundStyle PortalGunAlt = SoundID.Item115;

    /// <summary>Solar Eruption</summary>
    public static readonly SoundStyle SolarEruption = SoundID.Item116;

    /// <summary>Nebula Arcanum, Spirit Flame</summary>
    public static readonly SoundStyle NebulaArcanum = SoundID.Item117;

    /// <summary>Crystal Charge impact</summary>
    public static readonly SoundStyle CrystalChargeImpact = SoundID.Item118;

    /// <summary>Phantasm Dragon summoned</summary>
    public static readonly SoundStyle PhantasmDragon = SoundID.Item119;

    /// <summary>Ice Mist summoned</summary>
    public static readonly SoundStyle IceMist = SoundID.Item120;

    /// <summary>Lightning Orb summoned</summary>
    public static readonly SoundStyle LightningOrb = SoundID.Item121;

    /// <summary>Item122 - unused</summary>
    public static readonly SoundStyle Unused122 = SoundID.Item122;

    /// <summary>Lightning Ritual summoned</summary>
    public static readonly SoundStyle LightningRitual = SoundID.Item123;

    /// <summary>Phantasmal Bolt</summary>
    public static readonly SoundStyle PhantasmalBolt = SoundID.Item124;

    /// <summary>Phantasmal Bolt</summary>
    public static readonly SoundStyle PhantasmalBoltAlt = SoundID.Item125;

    /// <summary>Golf Clubs</summary>
    public static readonly SoundStyle GolfClubs = SoundID.Item126;

    /// <summary>Cracked Dungeon Bricks</summary>
    public static readonly SoundStyle CrackedDungeonBricks = SoundID.Item127;

    /// <summary>Golf Whistle</summary>
    public static readonly SoundStyle GolfWhistle = SoundID.Item128;

    /// <summary>Golf Ball sunk into a Golf Cup</summary>
    public static readonly SoundStyle GolfBallSunk = SoundID.Item129;

    /// <summary>Void Bag</summary>
    public static readonly SoundStyle VoidBag = SoundID.Item130;

    /// <summary>Item131 - unused</summary>
    public static readonly SoundStyle Unused131 = SoundID.Item131;

    /// <summary>Laser Drill</summary>
    public static readonly SoundStyle LaserDrill = SoundID.Item132;

    /// <summary>Ivy, Rain Song, Stellar Tune</summary>
    public static readonly SoundStyle IvyGuitar = SoundID.Item133;

    /// <summary>Ivy, Rain Song, Stellar Tune</summary>
    public static readonly SoundStyle RainSong = SoundID.Item134;

    /// <summary>Ivy, Rain Song, Stellar Tune</summary>
    public static readonly SoundStyle StellarTune = SoundID.Item135;

    /// <summary>Ivy, Rain Song, Stellar Tune</summary>
    public static readonly SoundStyle IvyAlt1 = SoundID.Item136;

    /// <summary>Ivy, Rain Song, Stellar Tune</summary>
    public static readonly SoundStyle IvyAlt2 = SoundID.Item137;

    /// <summary>Ivy, Rain Song, Stellar Tune</summary>
    public static readonly SoundStyle IvyAlt3 = SoundID.Item138;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet1 = SoundID.Item139;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet2 = SoundID.Item140;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet3 = SoundID.Item141;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet4 = SoundID.Item142;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet5 = SoundID.Item143;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet6 = SoundID.Item144;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet7 = SoundID.Item145;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet8 = SoundID.Item146;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet9 = SoundID.Item147;

    /// <summary>Drum Set</summary>
    public static readonly SoundStyle DrumSet10 = SoundID.Item148;

    /// <summary>Ammo Box</summary>
    public static readonly SoundStyle AmmoBox = SoundID.Item149;

    /// <summary>Projectile reflected by Biome Mimic, Selenian, Dreadnautilus or Shimmer Slime</summary>
    public static readonly SoundStyle ProjectileReflect = SoundID.Item150;

    /// <summary>Snake Charmer's Flute</summary>
    public static readonly SoundStyle SnakeCharmerFlute = SoundID.Item151;

    /// <summary>Whips</summary>
    public static readonly SoundStyle Whip1 = SoundID.Item152;

    /// <summary>Whips</summary>
    public static readonly SoundStyle Whip2 = SoundID.Item153;

    /// <summary>Queen Slime</summary>
    public static readonly SoundStyle QueenSlime1 = SoundID.Item154;

    /// <summary>Queen Slime</summary>
    public static readonly SoundStyle QueenSlime2 = SoundID.Item155;

    /// <summary>Celebration</summary>
    public static readonly SoundStyle Celebration = SoundID.Item156;

    /// <summary>Space Gun</summary>
    public static readonly SoundStyle SpaceGun = SoundID.Item157;

    /// <summary>Gray Zapinator, Orange Zapinator</summary>
    public static readonly SoundStyle Zapinator = SoundID.Item158;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight1 = SoundID.Item159;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight2 = SoundID.Item160;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight3 = SoundID.Item161;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight4 = SoundID.Item162;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight5 = SoundID.Item163;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight6 = SoundID.Item164;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLight7 = SoundID.Item165;

    /// <summary>Music Box recorded</summary>
    public static readonly SoundStyle MusicBox = SoundID.Item166;

    /// <summary>Queen Slime</summary>
    public static readonly SoundStyle QueenSlime3 = SoundID.Item167;

    /// <summary>Pogo Stick Mount</summary>
    public static readonly SoundStyle PogoStickMount = SoundID.Item168;

    /// <summary>Zenith</summary>
    public static readonly SoundStyle Zenith = SoundID.Item169;

    /// <summary>Dreadnautilus</summary>
    public static readonly SoundStyle Dreadnautilus1 = SoundID.Item170;

    /// <summary>Dreadnautilus</summary>
    public static readonly SoundStyle Dreadnautilus2 = SoundID.Item171;

    /// <summary>Dreadnautilus</summary>
    public static readonly SoundStyle Dreadnautilus3 = SoundID.Item172;

    /// <summary>Larva when struck, Abeemination</summary>
    public static readonly SoundStyle Abeemination = SoundID.Item173;

    /// <summary>KO Cannon</summary>pchit
    public static readonly SoundStyle KOCannon = SoundID.Item174;

    /// <summary>Slap Hand</summary>
    public static readonly SoundStyle SlapHand = SoundID.Item175;

    /// <summary>Shimmer</summary>
    public static readonly SoundStyle Shimmer = SoundID.Item176;

    /// <summary>Poo when struck or landed on</summary>
    public static readonly SoundStyle Poo = SoundID.Item177;

    /// <summary>Waffle's Iron</summary>
    public static readonly SoundStyle WafflesIron = SoundID.Item178;

    // ==================== NPC HIT SOUNDS ====================

    /// <summary>Generic NPC hit - placeholder</summary>
    public static readonly SoundStyle BoneHit = SoundID.NPCHit1;

    /// <summary>Bone Serpent, Cursed Skull, Dungeon Guardian, Skeleton variants, Skeletron</summary>
    public static readonly SoundStyle SkeletonHit = SoundID.NPCHit2;

    /// <summary>Burning Sphere, Chaos Ball, Corite, Detonating Bubble, Meteor Head, Water Sphere</summary>
    public static readonly SoundStyle ElementalHit = SoundID.NPCHit3;

    /// <summary>Crimson Axe, Cursed Hammer, Elf Copter, Enchanted Sword, Golem, Mimics, Probe, Skeletron Prime, The Destroyer, The Twins</summary>
    public static readonly SoundStyle BossHit = SoundID.NPCHit4;

    /// <summary>Pixie, Ice Elemental, Ice Golem</summary>
    public static readonly SoundStyle FairyHit = SoundID.NPCHit5;

    /// <summary>Werewolf, Evolution Beast, Stargazer, Twinkle Popper</summary>
    public static readonly SoundStyle WerewolfHit = SoundID.NPCHit6;

    /// <summary>Butcher, Everscream, Gingerbread Man, Granite Elemental, Ice Queen, Mourning Wood, Splinterling, Sroller, Turkor the Ungrateful, Wyvern</summary>
    public static readonly SoundStyle WyvernHit = SoundID.NPCHit7;

    /// <summary>Wall of Flesh</summary>
    public static readonly SoundStyle WallOfFleshHit = SoundID.NPCHit8;

    /// <summary>Leech, The Hungry, Creeper, Brain of Cthulhu, Vasculash</summary>
    public static readonly SoundStyle BrainHit = SoundID.NPCHit9;

    /// <summary>Generic placeholder</summary>
    public static readonly SoundStyle NPCHit10 = SoundID.NPCHit10;

    /// <summary>Mister Stabby, Snow Balla, Snowman Gangsta, Angry Tumbler, Crawltipede</summary>
    public static readonly SoundStyle SnowballHit = SoundID.NPCHit11;

    /// <summary>Unicorn, Headless Horseman</summary>
    public static readonly SoundStyle UnicornHit = SoundID.NPCHit12;

    /// <summary>Blood Jelly, Blood Feeder, Ichor Sticker, Sand Poacher</summary>
    public static readonly SoundStyle BloodJellyHit = SoundID.NPCHit13;

    /// <summary>Duke Fishron</summary>
    public static readonly SoundStyle DukeFishronHit = SoundID.NPCHit14;

    /// <summary>Target Dummy</summary>
    public static readonly SoundStyle TargetDummyHit = SoundID.NPCHit15;

    /// <summary>Target Dummy</summary>
    public static readonly SoundStyle TargetDummyHit2 = SoundID.NPCHit16;

    /// <summary>Target Dummy</summary>
    public static readonly SoundStyle TargetDummyHit3 = SoundID.NPCHit17;

    /// <summary>Blood Zombie, Zombie Merman</summary>
    public static readonly SoundStyle BloodZombieHit = SoundID.NPCHit18;

    /// <summary>Drippler, Flying Dutchman</summary>
    public static readonly SoundStyle DripperHit = SoundID.NPCHit19;

    /// <summary>Blood Crawler</summary>
    public static readonly SoundStyle BloodCrawlerHit = SoundID.NPCHit20;

    /// <summary>Demon, Voodoo Demon, Red Devil</summary>
    public static readonly SoundStyle DemonHit = SoundID.NPCHit21;

    /// <summary>Derpling</summary>
    public static readonly SoundStyle DerplingHit = SoundID.NPCHit22;

    /// <summary>Flying Snake, Sand Elemental</summary>
    public static readonly SoundStyle FlyingSnakeHit = SoundID.NPCHit23;

    /// <summary>Giant Tortoise, Ice Tortoise</summary>
    public static readonly SoundStyle TortoiseHit = SoundID.NPCHit24;

    /// <summary>Blue Jellyfish, Pink Jellyfish, Green Jellyfish</summary>
    public static readonly SoundStyle JellyfishHit = SoundID.NPCHit25;

    /// <summary>Lihzahrd</summary>
    public static readonly SoundStyle LihzahrdHit = SoundID.NPCHit26;

    /// <summary>Pigron</summary>
    public static readonly SoundStyle PigronHit = SoundID.NPCHit27;

    /// <summary>Vulture</summary>
    public static readonly SoundStyle VultureHit = SoundID.NPCHit28;

    /// <summary>Black Recluse, Wall Creeper</summary>
    public static readonly SoundStyle SpiderHit = SoundID.NPCHit29;

    /// <summary>Angry Nimbus</summary>
    public static readonly SoundStyle NimbusHit = SoundID.NPCHit30;

    /// <summary>Antlion, Antlion Charger, Giant Antlion Charger, Antlion Larva</summary>
    public static readonly SoundStyle AntlionHit = SoundID.NPCHit31;

    /// <summary>Antlion Swarmer</summary>
    public static readonly SoundStyle AntlionSwarmerHit = SoundID.NPCHit32;

    /// <summary>Crawdad</summary>
    public static readonly SoundStyle CrawdadHit = SoundID.NPCHit33;

    /// <summary>Deadly Sphere</summary>
    public static readonly SoundStyle DeadlySphereHit = SoundID.NPCHit34;

    /// <summary>Dr. Man Fly</summary>
    public static readonly SoundStyle DrManFlyHit = SoundID.NPCHit35;

    /// <summary>Dungeon Spirit</summary>
    public static readonly SoundStyle DungeonSpiritHit = SoundID.NPCHit36;

    /// <summary>Ghoul, Vile Ghoul, Tainted Ghoul, Dreamer Ghoul</summary>
    public static readonly SoundStyle GhoulHit = SoundID.NPCHit37;

    /// <summary>Giant Shelly</summary>
    public static readonly SoundStyle GiantShellyHit = SoundID.NPCHit38;

    /// <summary>Brain Scrambler, Gigazapper, Gray Grunt, Martian Engineer, Martian Officer, Ray Gunner, Scutlix Gunner</summary>
    public static readonly SoundStyle BrainScramblerHit = SoundID.NPCHit39;

    /// <summary>Goblin Warlock</summary>
    public static readonly SoundStyle GoblinWarlockHit = SoundID.NPCHit40;

    /// <summary>Granite Golem, Rock Golem</summary>
    public static readonly SoundStyle GolemHit = SoundID.NPCHit41;

    /// <summary>Martian Drone</summary>
    public static readonly SoundStyle MartianDroneHit = SoundID.NPCHit42;

    /// <summary>Bubble Shield</summary>
    public static readonly SoundStyle BubbleShieldHit = SoundID.NPCHit43;

    /// <summary>Mothron</summary>
    public static readonly SoundStyle MothronHit = SoundID.NPCHit44;

    /// <summary>Mushi Ladybug</summary>
    public static readonly SoundStyle MushiLadybugHit = SoundID.NPCHit45;

    /// <summary>Parrot</summary>
    public static readonly SoundStyle ParrotHit = SoundID.NPCHit46;

    /// <summary>The Possessed</summary>
    public static readonly SoundStyle ThePossessedHit = SoundID.NPCHit47;

    /// <summary>Psycho</summary>
    public static readonly SoundStyle PsychoHit = SoundID.NPCHit48;

    /// <summary>Reaper</summary>
    public static readonly SoundStyle ReaperHit = SoundID.NPCHit49;

    /// <summary>Salamander</summary>
    public static readonly SoundStyle SalamanderHit = SoundID.NPCHit50;

    /// <summary>Scutlix</summary>
    public static readonly SoundStyle ScutlixHit = SoundID.NPCHit51;

    /// <summary>Shadowflame Apparition</summary>
    public static readonly SoundStyle ShadowflameApparitionHit = SoundID.NPCHit52;

    /// <summary>Tesla Turret</summary>
    public static readonly SoundStyle TeslaTurretHit = SoundID.NPCHit53;

    /// <summary>Wraith</summary>
    public static readonly SoundStyle WraithHit = SoundID.NPCHit54;

    /// <summary>Lunatic Cultist</summary>
    public static readonly SoundStyle LunaticCultistHit = SoundID.NPCHit55;

    /// <summary>Phantasm Dragon</summary>
    public static readonly SoundStyle PhantasmDragonHit = SoundID.NPCHit56;

    /// <summary>Moon Lord, Moon Leech Clot</summary>
    public static readonly SoundStyle MoonLordHit = SoundID.NPCHit57;

    // ==================== NPC DEATH SOUNDS ====================

    /// <summary>Generic NPC death - placeholder</summary>
    public static readonly SoundStyle BoneDeath = SoundID.NPCDeath1;

    /// <summary>Frankenstein, Skeleton, Zombie, Clown, Face Monster, Lunatic Cultist, Target Dummy, and many others</summary>
    public static readonly SoundStyle SkeletonDeath = SoundID.NPCDeath2;

    /// <summary>Burning Sphere, Chaos Ball, Corite, Detonating Bubble, Meteor Head, Water Sphere</summary>
    public static readonly SoundStyle ElementalDeath = SoundID.NPCDeath3;

    /// <summary>Bats, Hellbat, Jungle Bat, Lava Bat, Spore Bat, Giant Flying Fox</summary>
    public static readonly SoundStyle BatDeath = SoundID.NPCDeath4;

    /// <summary>Bone Serpent, Everscream, Hellhound, Ice Queen, Mourning Wood, Predictor, Twinkle, Vortexian</summary>
    public static readonly SoundStyle BoneSerpentDeath = SoundID.NPCDeath5;

    /// <summary>Alien Hornet, Alien Queen, Chaos Elemental, Mimic variants, Mummy, Ghost, Vampire, Princess, and many others</summary>
    public static readonly SoundStyle AlienDeath = SoundID.NPCDeath6;

    /// <summary>Pixie, Ice Elemental, Ice Golem, Twinkle exploding</summary>
    public static readonly SoundStyle FairyDeath = SoundID.NPCDeath7;

    /// <summary>Wyvern</summary>
    public static readonly SoundStyle WyvernDeath = SoundID.NPCDeath8;

    /// <summary>Vile Spit</summary>
    public static readonly SoundStyle VileSpitDeath = SoundID.NPCDeath9;

    /// <summary>Wall of Flesh, Wall of Flesh Eye</summary>
    public static readonly SoundStyle WallOfFleshDeath = SoundID.NPCDeath10;

    /// <summary>Brain of Cthulhu</summary>
    public static readonly SoundStyle BrainDeath = SoundID.NPCDeath11;

    /// <summary>Eater of Worlds</summary>
    public static readonly SoundStyle EaterDeath = SoundID.NPCDeath12;

    /// <summary>Queen Bee</summary>
    public static readonly SoundStyle QueenBeeDeath = SoundID.NPCDeath13;

    /// <summary>Skeletron</summary>
    public static readonly SoundStyle SkeletronDeath = SoundID.NPCDeath14;

    /// <summary>Dungeon Guardian</summary>
    public static readonly SoundStyle DungeonGuardianDeath = SoundID.NPCDeath15;

    /// <summary>The Twins, Spore Zombie</summary>
    public static readonly SoundStyle TwinsDeath = SoundID.NPCDeath16;

    /// <summary>The Destroyer</summary>
    public static readonly SoundStyle DestroyerDeath = SoundID.NPCDeath17;

    /// <summary>Skeletron Prime</summary>
    public static readonly SoundStyle SkeletronPrimeDeath = SoundID.NPCDeath18;

    /// <summary>Plantera</summary>
    public static readonly SoundStyle PlanteraDeath = SoundID.NPCDeath19;

    /// <summary>Golem</summary>
    public static readonly SoundStyle GolemDeath = SoundID.NPCDeath20;

    /// <summary>Duke Fishron</summary>
    public static readonly SoundStyle DukeFishronDeath = SoundID.NPCDeath21;

    /// <summary>Empress of Light</summary>
    public static readonly SoundStyle EmpressOfLightDeath = SoundID.NPCDeath22;

    /// <summary>Eye of Cthulhu</summary>
    public static readonly SoundStyle EyeOfCthulhuDeath = SoundID.NPCDeath23;

    /// <summary>King Slime</summary>
    public static readonly SoundStyle KingSlimeDeath = SoundID.NPCDeath24;

    /// <summary>Slime variants</summary>
    public static readonly SoundStyle SlimeDeath = SoundID.NPCDeath25;

    /// <summary>Demon Eye, Wandering Eye</summary>
    public static readonly SoundStyle DemonEyeDeath = SoundID.NPCDeath26;

    /// <summary>Goblin Scout, Goblin Warrior, Goblin Archer, Goblin Sorcerer, Goblin Peon</summary>
    public static readonly SoundStyle GoblinDeath = SoundID.NPCDeath27;

    /// <summary>Harpy, Harpies</summary>
    public static readonly SoundStyle HarpyDeath = SoundID.NPCDeath28;

    /// <summary>Undead Viking, Skeleton Merchant</summary>
    public static readonly SoundStyle SkeletonMerchantDeath = SoundID.NPCDeath29;

    /// <summary>Blood Crawler, Crimson Axe, Crimson Eye, Floaty Gross, Wary Devourer</summary>
    public static readonly SoundStyle CrimsonDeath = SoundID.NPCDeath30;

    /// <summary>Corrupt Slime, Eater of Souls, Creeper, Corruptor</summary>
    public static readonly SoundStyle CorruptDeath = SoundID.NPCDeath31;

    /// <summary>Sand Shark, Sand Poacher, Sand Slime, Tomb Crawler</summary>
    public static readonly SoundStyle SandSharkDeath = SoundID.NPCDeath32;

    /// <summary>Hornet, Jungle Slime, Spike Ball, Jungle Creeper</summary>
    public static readonly SoundStyle HornetDeath = SoundID.NPCDeath33;

    /// <summary>Jungle Bat, Jungle Crate, Jungle Plant</summary>
    public static readonly SoundStyle JungleBatDeath = SoundID.NPCDeath34;

    /// <summary>Man Eater, Piranha, Snapper</summary>
    public static readonly SoundStyle ManEaterDeath = SoundID.NPCDeath35;

    /// <summary>Poacher, Rogue, Rogue Ninja</summary>
    public static readonly SoundStyle RogueDeath = SoundID.NPCDeath36;

    /// <summary>Archer, Elf Archer, Pincushion Ghost</summary>
    public static readonly SoundStyle ArcherDeath = SoundID.NPCDeath37;

    /// <summary>Mummy, Cursed Mummy, Mummy variants</summary>
    public static readonly SoundStyle MummyDeath = SoundID.NPCDeath38;

    /// <summary>Dark Caster, Light Caster, Angry Bones, Cursed Skull</summary>
    public static readonly SoundStyle CasterDeath = SoundID.NPCDeath39;

    /// <summary>Paladin, Bone Lee, Necromancer, Paladin's Hammer</summary>
    public static readonly SoundStyle PaladinDeath = SoundID.NPCDeath40;

    /// <summary>Lava Slime, Demon, Cacodemon, Fire Imp, Hell Armored Bones</summary>
    public static readonly SoundStyle LavaDeath = SoundID.NPCDeath41;

    /// <summary>Blue Armored Bones, Cursed Armored Bones, Green Armored Bones</summary>
    public static readonly SoundStyle ArmoredBonesDeath = SoundID.NPCDeath42;

    /// <summary>Wraith, Angry Bones</summary>
    public static readonly SoundStyle WraithDeath = SoundID.NPCDeath43;

    /// <summary>Dragon, Wyvern variants</summary>
    public static readonly SoundStyle DragonDeath = SoundID.NPCDeath44;

    /// <summary>Giant Bat</summary>
    public static readonly SoundStyle GiantBatDeath = SoundID.NPCDeath45;

    /// <summary>Wandering Eye</summary>
    public static readonly SoundStyle WanderingEyeDeath = SoundID.NPCDeath46;

    /// <summary>Black Slime, Corrupt variants</summary>
    public static readonly SoundStyle BlackSlimeDeath = SoundID.NPCDeath47;

    /// <summary>Vulture</summary>
    public static readonly SoundStyle VultureDeath = SoundID.NPCDeath48;

    /// <summary>Goblin Peon, Goblin Thief</summary>
    public static readonly SoundStyle GoblinThiefDeath = SoundID.NPCDeath49;

    /// <summary>Chaos Elemental</summary>
    public static readonly SoundStyle ChaosElementalDeath = SoundID.NPCDeath50;

    /// <summary>Mimic, Light Mimic, Dark Mimic</summary>
    public static readonly SoundStyle MimicDeath = SoundID.NPCDeath51;

    /// <summary>Illuminant Bat, Illuminant Slime, Illuminant Starite</summary>
    public static readonly SoundStyle IlluminantDeath = SoundID.NPCDeath52;

    /// <summary>Nailhead, Rusty Armored Bones variants</summary>
    public static readonly SoundStyle NailheadDeath = SoundID.NPCDeath53;

    /// <summary>Meteor Head variants</summary>
    public static readonly SoundStyle MeteorHeadDeath = SoundID.NPCDeath54;

    /// <summary>Granite Golem, Granite Elemental</summary>
    public static readonly SoundStyle GraniteGolemDeath = SoundID.NPCDeath55;

    /// <summary>Marble Golem, Marble Elemental</summary>
    public static readonly SoundStyle MarbleGolemDeath = SoundID.NPCDeath56;

    /// <summary>Hallowed Mimic, Hallowed creature</summary>
    public static readonly SoundStyle HallowedMimicDeath = SoundID.NPCDeath57;

    /// <summary>Queen Slime</summary>
    public static readonly SoundStyle QueenSlimeDeath = SoundID.NPCDeath58;

    /// <summary>Mothron</summary>
    public static readonly SoundStyle MothronDeath = SoundID.NPCDeath59;

    /// <summary>Pumpking</summary>
    public static readonly SoundStyle PumpkingDeath = SoundID.NPCDeath60;

    /// <summary>Mourning Wood</summary>
    public static readonly SoundStyle MourningWoodDeath = SoundID.NPCDeath61;

    /// <summary>Santa-NK1</summary>
    public static readonly SoundStyle SantaNK1Death = SoundID.NPCDeath62;

    /// <summary>Ice Queen</summary>
    public static readonly SoundStyle IceQueenDeath = SoundID.NPCDeath63;

    /// <summary>Everscream</summary>
    public static readonly SoundStyle EverscreamDeath = SoundID.NPCDeath64;

    /// <summary>Cultist, Lunatic Cultist</summary>
    public static readonly SoundStyle CultistDeath = SoundID.NPCDeath65;

    /// <summary>Moon Lord</summary>
    public static readonly SoundStyle MoonLordDeath = SoundID.NPCDeath66;

    // ==================== UI & ENVIRONMENTAL SOUNDS ====================

    /// <summary>Grass blocks struck by Leaf Blower or Chlorophyte Arrow, plant-based blocks impact</summary>
    public static readonly SoundStyle Grass = SoundID.Grass;

    /// <summary>Item picked up</summary>
    public static readonly SoundStyle ItemGrabbed = SoundID.Grab;

    /// <summary>Opening a Door, Trap Door, or Tall Gate</summary>
    public static readonly SoundStyle DoorOpen = SoundID.DoorOpen;

    /// <summary>Closing a Door</summary>
    public static readonly SoundStyle DoorClose = SoundID.DoorClosed;

    /// <summary>UI opened</summary>
    public static readonly SoundStyle MenuOpen = SoundID.MenuOpen;

    /// <summary>UI closed</summary>
    public static readonly SoundStyle MenuClose = SoundID.MenuClose;

    /// <summary>UI elements hovered</summary>
    public static readonly SoundStyle MenuTick = SoundID.MenuTick;

    /// <summary>Pots struck, Molotov Cocktail impact, glass-based blocks impact</summary>
    public static readonly SoundStyle Shatter = SoundID.Shatter;

    /// <summary>Summoning an NPC: Eye of Cthulhu, Skeletron, Skeletron Prime, The Twins</summary>
    public static readonly SoundStyle BossSummon = SoundID.Roar;

    /// <summary>Worm AI digging (additional roar variant)</summary>
    public static readonly SoundStyle WormDigging = SoundID.Roar;

    /// <summary>Performing a mid-air jump with an extra jump accessory or mount</summary>
    public static readonly SoundStyle DoubleJump = SoundID.DoubleJump;

    /// <summary>Running with Hermes Boots, Flurry Boots, Dunerider Boots, Sailfish Boots or upgrades</summary>
    public static readonly SoundStyle Running = SoundID.Run;

    /// <summary>Coins placed, struck, or used in transactions</summary>
    public static readonly SoundStyle Coins = SoundID.Coins;

    /// <summary>Water contact or exit, Magic Conch teleport, Shellphone teleport to Ocean</summary>
    public static readonly SoundStyle SplashWater = SoundID.Splash;

    /// <summary>Chest unlocked</summary>
    public static readonly SoundStyle Unlock = SoundID.Unlock;

    /// <summary>Player begins drowning</summary>
    public static readonly SoundStyle Drown = SoundID.Drown;

    /// <summary>Chat window toggled</summary>
    public static readonly SoundStyle Chat = SoundID.Chat;

    /// <summary>Mana fully restored, end of parry cooldown for Brand of the Inferno, end of projectile cooldown for Beam Sword, etc</summary>
    public static readonly SoundStyle MaxMana = SoundID.MaxMana;

    /// <summary>Stone-based blocks and walls when struck</summary>
    public static readonly SoundStyle Tink = SoundID.Tink;

    /// <summary>Mech sound - Most mechanism triggers activation, chat message sent</summary>
    public static readonly SoundStyle Mech = SoundID.Mech;

    // ==================== AMBIENT/CRITTER SOUNDS ====================

    /// <summary>Duck, Mallard Duck</summary>
    public static readonly SoundStyle Duck = SoundID.Duck;

    /// <summary>Frog, Gold Frog</summary>
    public static readonly SoundStyle Frog = SoundID.Frog;

    /// <summary>Bird, Blue Jay, Cardinal, Gold Bird</summary>
    public static readonly SoundStyle Bird = SoundID.Bird;

    /// <summary>Mouse, Rat, Gold Mouse</summary>
    public static readonly SoundStyle Critter = SoundID.Critter;

    /// <summary>Waterfalls nearby ambient</summary>
    public static readonly SoundStyle Waterfall = SoundID.Waterfall;

    /// <summary>Lavafalls nearby ambient</summary>
    public static readonly SoundStyle Lavafall = SoundID.Lavafall;

    /// <summary>Dripping Water impact</summary>
    public static readonly SoundStyle Drip = SoundID.Drip;

    /// <summary>Thunderstorm</summary>
    public static readonly SoundStyle Thunder = SoundID.Thunder;

    /// <summary>Seagull</summary>
    public static readonly SoundStyle Seagull = SoundID.Seagull;

    /// <summary>Dolphin</summary>
    public static readonly SoundStyle Dolphin = SoundID.Dolphin;

    /// <summary>Owl</summary>
    public static readonly SoundStyle Owl = SoundID.Owl;

    /// <summary>Yellow Cockatiel, Gray Cockatiel</summary>
    public static readonly SoundStyle Cockatiel = SoundID.Cockatiel;

    /// <summary>Scarlet Macaw, Blue Macaw</summary>
    public static readonly SoundStyle Macaw = SoundID.Macaw;

    /// <summary>Toucan</summary>
    public static readonly SoundStyle Toucan = SoundID.Toucan;

    // ==================== SPECIAL SOUNDS ====================

    /// <summary>Camera Mode Screenshot or Snapshot taken</summary>
    public static readonly SoundStyle Camera = SoundID.Camera;

    /// <summary>Researching an item</summary>
    public static readonly SoundStyle Research = SoundID.Research;

    /// <summary>Research complete</summary>
    public static readonly SoundStyle ResearchComplete = SoundID.ResearchComplete;

    /// <summary>Coins picked up</summary>
    public static readonly SoundStyle CoinPickup = SoundID.CoinPickup;

    // ==================== MUSIC/INSTRUMENT SOUNDS ====================

    /// <summary>Guitar C (Ivy, Rain Song, Stellar Tune)</summary>
    public static readonly SoundStyle GuitarC = SoundID.GuitarC;

    /// <summary>Guitar D (Ivy, Rain Song, Stellar Tune)</summary>
    public static readonly SoundStyle GuitarD = SoundID.GuitarD;

    /// <summary>Guitar Em (Ivy, Rain Song, Stellar Tune)</summary>
    public static readonly SoundStyle GuitarEm = SoundID.GuitarEm;

    /// <summary>Guitar G (Ivy, Rain Song, Stellar Tune)</summary>
    public static readonly SoundStyle GuitarG = SoundID.GuitarG;

    /// <summary>Guitar Bm (Ivy, Rain Song, Stellar Tune)</summary>
    public static readonly SoundStyle GuitarBm = SoundID.GuitarBm;

    /// <summary>Guitar Am (Ivy, Rain Song, Stellar Tune)</summary>
    public static readonly SoundStyle GuitarAm = SoundID.GuitarAm;

    /// <summary>Drum Set - Hi Hat</summary>
    public static readonly SoundStyle DrumHiHat = SoundID.DrumHiHat;

    /// <summary>Drum Set - Tom High</summary>
    public static readonly SoundStyle DrumTomHigh = SoundID.DrumTomHigh;

    /// <summary>Drum Set - Tom Low</summary>
    public static readonly SoundStyle DrumTomLow = SoundID.DrumTomLow;

    /// <summary>Drum Set - Tom Mid</summary>
    public static readonly SoundStyle DrumTomMid = SoundID.DrumTomMid;

    /// <summary>Drum Set - Closed Hi Hat</summary>
    public static readonly SoundStyle DrumClosedHiHat = SoundID.DrumClosedHiHat;

    /// <summary>Drum Set - Cymbal 1</summary>
    public static readonly SoundStyle DrumCymbal1 = SoundID.DrumCymbal1;

    /// <summary>Drum Set - Cymbal 2</summary>
    public static readonly SoundStyle DrumCymbal2 = SoundID.DrumCymbal2;

    /// <summary>Drum Set - Kick</summary>
    public static readonly SoundStyle DrumKick = SoundID.DrumKick;

    /// <summary>Drum Set - Tama Snare</summary>
    public static readonly SoundStyle DrumTamaSnare = SoundID.DrumTamaSnare;

    /// <summary>Drum Set - Floor Tom</summary>
    public static readonly SoundStyle DrumFloorTom = SoundID.DrumFloorTom;
}
